### ISSUE TITLE
Move VM to Docker

### ISSUE THREAD

**Issue by kpinnipa** [comalvirdi/TheAltRockers#8]
Transfer VM Image to Docker.
Steps:

Link to instructions: [VM Migration](https://www.vinnie.work/blog/2021-03-19-virtualmachine-to-docker/)

**Comment by jacob-gold** [comment]
Sort of completed. Couldn't transfer our specific VM image with the code from last quarter but did find a repo that does have crispr in a Docker image. We should be able to add to this container, including code to take crispr output -> pipeline -> dash website

https://hub.docker.com/r/lucapinello/crispresso/
https://github.com/lucapinello/CRISPResso

**Comment by jacob-gold** [comment]
https://github.com/pinellolab/crispresso2 (non-deprecated repo link)
